### ISSUE TITLE
Please specify the license

### ISSUE THREAD

**Issue by JayLiangs** [Birch-san/diffusers-play#7]
Hi Birch-san,

Thank you for developing such a great product. However, I couldn't locate any license information in the project files. Could you please clarify which license applies to this project, and specifically whether it can be used for commercial purposes?

**Comment by Birch-san** [comment]
added BSD 3-clause license.  
https://github.com/Birch-san/diffusers-play/commit/96f6d0359979d47e4dc27c9675cbb2e9326465e6

commercial use is fine, but please credit me somewhere your user will see, with a link to this repository.

**Comment by JayLiangs** [comment]
Thanks a lot!!!
